-- ============================================================
-- DATABASE CHANGES FOR CONTENT TYPE SELECTION AND REEL SCRIPTS
-- ============================================================
-- Execute these SQL statements in your Supabase SQL editor
-- ============================================================

-- 1. Create reel_scripts table
-- ============================================================
CREATE TABLE IF NOT EXISTS reel_scripts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id TEXT NOT NULL,
  action_id UUID REFERENCES rl_actions(id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  business_id UUID,
  topic TEXT,
  script_content TEXT NOT NULL,
  status TEXT DEFAULT 'generated', -- generated | in_production | completed | cancelled
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_reel_scripts_post_id ON reel_scripts(post_id);
CREATE INDEX IF NOT EXISTS idx_reel_scripts_business_id ON reel_scripts(business_id);
CREATE INDEX IF NOT EXISTS idx_reel_scripts_status ON reel_scripts(status);
CREATE INDEX IF NOT EXISTS idx_reel_scripts_action_id ON reel_scripts(action_id);

-- ============================================================
-- 2. Add content_type column to rl_actions table
-- ============================================================
ALTER TABLE rl_actions 
ADD COLUMN IF NOT EXISTS content_type TEXT; -- 'post' or 'reel'

-- Create index for content_type
CREATE INDEX IF NOT EXISTS idx_rl_actions_content_type ON rl_actions(content_type);

-- ============================================================
-- 3. Add content_type column to post_contents table (optional)
-- ============================================================
ALTER TABLE post_contents 
ADD COLUMN IF NOT EXISTS content_type TEXT; -- 'post' or 'reel'

-- Create index for content_type
CREATE INDEX IF NOT EXISTS idx_post_contents_content_type ON post_contents(content_type);

-- 4. Add post_script column to post_contents table
-- ============================================================
ALTER TABLE post_contents 
ADD COLUMN IF NOT EXISTS post_script TEXT; -- Human-readable script explaining how to use the post content

-- Create index for post_script (optional, for full-text search if needed)
-- CREATE INDEX IF NOT EXISTS idx_post_contents_post_script ON post_contents USING gin(to_tsvector('english', post_script));

-- ============================================================
-- NOTES:
-- ============================================================
-- 1. The reel_scripts table stores human-followable reel scripts
--    generated by the AI system
-- 2. The content_type column in rl_actions tracks whether the
--    action was for a 'post' or 'reel'
-- 3. The content_type column in post_contents is optional but
--    recommended for tracking content type at the post level
-- 4. The post_script column stores human-readable instructions
--    explaining how to use the generated post content (caption + image)
-- 5. All changes are backward compatible - existing records will
--    have NULL content_type which defaults to 'post' behavior
-- ============================================================

